<a href="https://colab.research.google.com/github/nafl13/ICT_DSA/blob/Daily_tasks/Numpy_DT.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Q1

In [ ]:
import numpy as np

In [ ]:
def find_max(num1,num2,num3):
  if num1>num2 and num1>num3:
    print('max number is: ',num1)
  elif num2>num1 and num2>num3:
    print('max number is: ',num2)
  else:
    print('max number is: ',num3)

In [ ]:
num1=10
num2=50
num3=20
find_max(num1,num2,num3)




max number is:  50


Q2

In [ ]:
def area_circle():
  r=int(input('Enter the radius: '))
  pi=3.14
  print('area= ',pi*r**2)



In [ ]:
area_circle()

Enter the radius: 5
area=  78.5


Q3

In [ ]:
def is_prime():
  num=int(input('Enter the number: '))
  if num <= 1:
     return False
  for i in range(2, int(num**0.5) + 1):
     if num % i == 0:
      return False
  return True

In [ ]:
is_prime()

Enter the number: 10


False

Q4

In [ ]:
#pallindrone
def is_pallindrone():
  w=input("Enter the word: ")
  w=w.replace(" ","")
  if w==w[::-1]:
    return True
  else:
    return False







In [ ]:
is_pallindrone()

Enter the word: abc


False

Q5

In [ ]:
def sum(l):
  total=0
  for i in l:
    total+=i
  return total




In [ ]:
l=[1,2,3,4,5]
sum(l)


15

Q6

In [ ]:
def avg(a):
  total=0
  for i in a:
    total+=i
    return total/len(a)

In [ ]:
a=[1,2,3,4,5]
avg(a)


0.2

Q7

In [ ]:
arr = [12, 15, 7, 3, 8, 16, 25]
def kth_largest_element(k):
    global arr
    arr.sort(reverse = True)
    return arr[k-1]
k = 5
print(f"The {k}th largest element = {kth_largest_element(k)}")


The 5th largest element = 8


Q8

In [ ]:
def sum_of_digit(n):
    if n< 10:
        return n
    else:
        return n%10 + sum_of_digit(n/10)
number = int(input("Enter number: "))
digit_sum = sum_of_digit(number)
print("Sum of digit of number %d is %d." % (number,digit_sum))

Enter number: 123
Sum of digit of number 123 is 6.


Q9

In [ ]:
def CalculatePower(N,X):
  P=1
  for i in range(1, X+1):
    P=P*N
  return P

N,X=10,3
print(CalculatePower(N,X))

1000


Q10

In [ ]:
def gcd(a, b):
  if b == 0:
    return a
  else:
    return gcd(b, (a % b))

gcd(10,15)

5

Q11

In [ ]:
n=np.arange(0,10)
print(n)

[0 1 2 3 4 5 6 7 8 9]


Q12

In [ ]:
d=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


Q13

In [ ]:
i=np.identity(3)
print(i)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Q14

In [ ]:
r=np.random.randint(1,100,5)
print(r)
mean=np.mean(r)
print('mean value : ',mean)
sd=np.std(r)
print('standard deviation : ',sd)

[42  2 69 81 99]
mean value :  58.6
standard deviation :  33.82661673889365


Q15

In [ ]:
ex=np.arange(10,21)
ex[0:5]

array([10, 11, 12, 13, 14])

Q16

In [ ]:
sr=np.arange(0,16)
sr=sr.reshape(4,4)
sr

print(sr[1,:])

[4 5 6 7]


Q17

In [ ]:
a1=np.arange(1,6)
a2=np.arange(6,11)
print(a1+a2)

[ 7  9 11 13 15]


Q18

In [ ]:
ra=np.random.rand(10)
ra[ra>0.5]=0
print(ra)


[0.         0.17548017 0.         0.         0.45221713 0.49578452
 0.         0.         0.41614391 0.02368855]
